### ISSUE TITLE
No icon on Ubuntu Dock (snap install)

### ISSUE THREAD

**Issue by luispjoaquim** [oscartbeaumont/ElectronPlayer#11]
When running the app it does not show the icon in the Ubuntu dock.

Instalation details:

Ubuntu 19.04
snap install
electronplayer  v.2.0.2

Screenshots:

![Screenshot from 2019-04-18 08-31-45](https://user-images.githubusercontent.com/29508215/56344089-7b2c0200-61b4-11e9-9696-00a9ba80504f.png)

![Screenshot from 2019-04-18 08-28-27](https://user-images.githubusercontent.com/29508215/56343903-fd67f680-61b3-11e9-9d21-68f861c35328.png)

**Comment by oscartbeaumont** [comment]
I have no clue what's causing this because it works fine on my pretty much blank install of PopOS. Can you try the `.AppImage` in the [Github Releases](https://github.com/oscartbeaumont/ElectronPlayer/releases) to see if the issue is just for the snap or the entire application.

**Comment by luispjoaquim** [comment]
Same issue with .appimage

appimage on the left, snap when the right

![Screenshot from 2019-04-18 11-27-40](https://user-images.githubusercontent.com/29508215/56354993-16c96c80-61cd-11e9-9e00-3a02bcdc443d.png)

**Comment by oscartbeaumont** [comment]
I just installed Ubuntu 19.04 in a VM and can reproduce the error, I am going to investigate the cause.

**Comment by luispjoaquim** [comment]
Thanks.
If you need anything from my side please let me know.
LJ

**Comment by oscartbeaumont** [comment]
I hopefully fixed it in version 2.0.3, please update your snap using the command below and see if the issue is fixed.
```bash
sudo snap refresh electronplayer
```

**Comment by luispjoaquim** [comment]
Perfect !!!
Many thanks.
LJ

![Screenshot from 2019-04-18 15-21-05](https://user-images.githubusercontent.com/29508215/56367652-a2eb8c00-61ed-11e9-8498-d2147d5850f3.png)
