### ISSUE TITLE
Block youtube ads

### ISSUE THREAD

**Issue by jellelicht** [oscartbeaumont/ElectronPlayer#14]
It would be nice to offer the option to block advertisements on youtube.

**Comment by oscartbeaumont** [comment]
That would be a cool idea. I will look into adding it in the future (possibly the next few weeks).

**Comment by Rastafabisch** [comment]
I second that. In my experience the block lists from adguard (free safari extension) are the most effective, and are individually accessible from the extensions menu.

**Comment by oscartbeaumont** [comment]
I had a look into doing this today and it was more difficult than I expected but this is still definitely in the roadmap.

**Comment by Rastafabisch** [comment]
Thanks for sharing and keeping us up to date. In case it's helpful there is a [spezial YouTube only blocker](https://safari-extensions.apple.com/details/?id=com.add0n.youtube.adblocker-RED8XKG2R4) which might have blacklist which are easier to implement being stripped down to this use case only.

**Comment by oscartbeaumont** [comment]
For this issue, I am going to try and do a general ad and privacy block so it can apply to any streaming service (no that any other default ones require it). I would also like to allow the blocking lists to be configurable so an end user could tinker if they desired. I will look into the ad blocking method of that plugin you linked and see how to do it in Electron.

**Comment by murabitothegit** [comment]
think the code of ublock origin or privacy badger might help? that's what i use in firefox and it doesn't break any of the sites i've accessed that are available in electronplayer using those. i'm afraid i don't know much about electron either... i love not having to open a browser to use netflx though^^'.

**Comment by actionjackbarker** [comment]
Is there any update on this feature?

**Comment by oscartbeaumont** [comment]
I have done some work but I haven't got anything that is good enough to publish. The only real way to do Adblocking without spending a large amount of time is via DNS based Adblocking in Electron. I need a DNS adblock list that blocks YouTube ads but isn't giant and doesn't takes up 10 times the RAM of the base app. If you know of any let me know.

**Comment by remusao** [comment]
Hey @oscartbeaumont,

I am maintaining a pure-JavaScript [adblocker library](https://github.com/cliqz-oss/adblocker) with fist-class Electron support. It only takes a [few lines to setup](https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-electron#usage).

It's really fast and memory friendly; and is able to block as many ads as web browser extensions (which includes Youtube ads). Maybe that would solve your use-case!

Best,
Rémi

**Comment by oscartbeaumont** [comment]
I had a quick look and that looks great to do Adblocking. I will implement it into the codebase for the next release which should hopefully be soon.

**Comment by oscartbeaumont** [comment]
I have added this feature to the master and a new version will be released sometime soon. A huge thanks to @remusao, I spent hours looking and trying to develop my own solution with no luck. Your adblocker solution and your library is perfect for this app.
This feature is by default. You can enable in the Settings menu of the application.
