### ISSUE TITLE
register URLs to the OS (open YouTube in ElectronPlayer)

### ISSUE THREAD

**Issue by Rastafabisch** [oscartbeaumont/ElectronPlayer#18]
Is it possible to make the OS default browser (for instance Safari) open YouTube URLs in ElectronPlayer be default (if desired)? If possible at all this properly should be googled via a setting.

**Comment by oscartbeaumont** [comment]
If I had to guess I would assume this is not possible to cause for example Youtube's domain to launch the app but I will investigate and report back. Maybe there would be a Chrome/Safari/etc extension that could be used to give this functionality.

**Comment by oscartbeaumont** [comment]
From my research, this isn't really easily possible. You can define custom URLs like `electronplayer://menu` which could launch the application but I can not see any way of overriding certain http/s URLS. I assume this functionality could be created with a Safari or Chrome or ect extension but that is not really in the scope of this project. You could have the extension that detects set URLs ie. 'https://youtube.com' and then redirect them to `electronplayer://openurl?url=urlhere`. I could add support for those custom protocol links if you are interested in building this. If you do decide to build this please contact me if you have any questions and I can link to it in the README if you finish it, for others who want to use it.
