### ISSUE TITLE
Netflix won't load

### ISSUE THREAD

**Issue by gittur** [oscartbeaumont/ElectronPlayer#22]
Hey, Just installed electronplayer and it seems that everything works great other than Netflix. It just stuck at the loading screen.
![image](https://user-images.githubusercontent.com/39214614/56861492-8eec1b00-69a1-11e9-8f05-0ebfc8fe5ede.png)

It just stuck here and keeps loading for ever and ever, without starting. 

P.S: Im using on electronplayer with i3 window manager

**Comment by Scrumplex** [comment]
Can you open the Developer Tools (Ctrl+Shift+I), open the Network tab, click on Netflix and create a screenshot?

**Comment by gittur** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/39214614/56861695-aa582580-69a3-11e9-8c53-80b51500749a.png)

**Comment by gittur** [comment]
Header Info:

Request URL: https://netflix.com/browse
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) electronplayer/2.0.4 Chrome/66.0.3359.181 Electron/3.1.8 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: 6D46C28F52983507D9331EB2A94702E0

**Comment by Scrumplex** [comment]
Dies Netflix work in other Browsers? Looks Mike this is a network problem.

**Comment by oscartbeaumont** [comment]
It does look like a network problem as your request is not being replied to by Netflix's servers. I checked the Netflix status page [here](https://help.netflix.com/en/is-netflix-down) and it reports that there are no major problems on their end. Do any of the other services in ElectronPlayer work and does your main browser have a connection to Netflix?

**Comment by gittur** [comment]
Hey, It started working now. Youtube, Twitch etc were working properly while Netflix was not so don't know if it was a network thing or not. Anyways really appreciate the help and great app.

Thank you !
