### ISSUE TITLE
Relaunching ElectronPlayer Netflix Multiple Tabs Bug

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/ElectronPlayer#23]
Some of the options require restarting ElectronPlayer to apply due to how Electron works. If you start playing a show on Netflix and then enable an option that requires the restart eg. frameless window or Mac Picture in Picture, It will restart and put you back on the same page as you previously had open but Netflix will show an error saying "Multiple Netflix Tabs". A simple reload of the page removes the error and allows you to continue watching your show.

@Scrumplex I thought I see if you have any ideas on what to do to fix this.

**Comment by Scrumplex** [comment]
If I had to guess, it's because it is restarting too fast and Netflix hasn't figured out by then, that the old stream has been closed. We should either try to gracefully close Netflix somehow or just have a restart delay

**Comment by oscartbeaumont** [comment]
This has been fixed now. Instead of restarting the entire application I now just destroy and recreate the browser window which doesn't cause the bugs and is also much faster due to it just resetting the browser window state and not exiting the entire application.
