### ISSUE TITLE
Enabling "Frameless Window" disables navigation

### ISSUE THREAD

**Issue by ToughGuyKunio** [oscartbeaumont/ElectronPlayer#24]
When I enable the Framless Window-option - clicking on Netflix, Youtube, etc icons stops working, instead when I click on them I drag the window around and double clicking makes the application fullscreen. Also couldn't find a way to disable framless windows, so I had to edit the Config.json to get it to work normally.

OS: Ubuntu 18.10
ElectronPlayer Version 2.0.4 installed from Snap Store

**Comment by oscartbeaumont** [comment]
In the latest version (2.0.4) there should be a cross in the top left of the window that allows you to exit frameless window mode. I will look into this further.

**Comment by ToughGuyKunio** [comment]
Thanks for looking into it. The X is there but when i click on it it just moves the window around.

**Comment by oscartbeaumont** [comment]
Sorry, it had taken this long to do the release. Life has got really busy.
