### ISSUE TITLE
Option to hide scrollbar

### ISSUE THREAD

**Issue by StorageB** [oscartbeaumont/ElectronPlayer#25]
It would be nice if there was an option to disable the visibility of the scrollbar on the right side of the player. It would look much better (especially in full screen or frameless window mode) if this could be hidden.

**Comment by oscartbeaumont** [comment]
This has now been fixed. A release will be pushed live within the next couple of days.

**Comment by oscartbeaumont** [comment]
Sorry, it had taken this long to do the release. Life has got really busy.
