### ISSUE TITLE
Option to start player in full screen mode

### ISSUE THREAD

**Issue by StorageB** [oscartbeaumont/ElectronPlayer#26]
It would be great if there was an option to launch the player in full screen mode. This would particularly be useful where used on a media center PC (connected to a TV) that is set to launch the player at boot.

**Comment by oscartbeaumont** [comment]
Does the existing "Always on Top" setting not work. It should remember your settings between restart (unless it recently got broken in some major changes that happened, then it needs fixing).

**Comment by oscartbeaumont** [comment]
This has been fixed in the master. If you are able to test it and report back if it works. I will release a new version of the app in the near future.

**Comment by StorageB** [comment]
I tested it and it's working well for me on Ubuntu 18.04. Thank you!
