### ISSUE TITLE
error: snap "electronplayer" is not available on stable for this architecture (i386)

### ISSUE THREAD

**Issue by osde8info** [oscartbeaumont/ElectronPlayer#29]
$ snap install electronplayer
error: snap "electronplayer" is not available on stable for this architecture (i386) but exists on
       other architectures (amd64).

$ uname -a
Linux vbox-xubu 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:20:43 UTC 2019 i686 i686 i686 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by oscartbeaumont** [comment]
I am going to look into this. This project uses `electron-builder` as its build system so hopefully they have an option for this.

**Comment by osde8info** [comment]
sorry my fault i think i was trying to install it on 32 bit xubuntu i will retry on 64 bit xubuntu

**Comment by osde8info** [comment]
now works fine

$ snap install electronplayer
2019-05-29T18:50:01+01:00 INFO Waiting for restart...
electronplayer 2.0.4 from Oscar Beaumont (oscartbeaumont) installed
