### ISSUE TITLE
Doesn't launch in Ubuntu 19.04

### ISSUE THREAD

**Issue by peliopoulos** [oscartbeaumont/ElectronPlayer#34]
In Ubuntu 19.04, the window flashes for less than a second and disappears. 

version 2.07 of Electron Player

**Comment by oscartbeaumont** [comment]
Please refer to issue #6 and see if the solution there helps. Reinstalling is also a good idea to see if that helps.

**Comment by peliopoulos** [comment]
This is when I try to run it from terminal:

snap run electronplayer

(electronplayer:13325): Gtk-WARNING **: 12:11:50.575: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/electronplayer/9/data-dir/icons/Yaru/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)

**Comment by peliopoulos** [comment]
This is the second time I have run into this issue; I already uninstalled and reinstalled when it happened earlier

**Comment by oscartbeaumont** [comment]
I am really not sure what is causing this and so I can't help you. Are you sure it is just my snap or all snaps? Is it just the snap version or does the bug occur with the Appimage version? I had a quick look and I couldn't find any errors in `electron` or `electron-builder` which seem to be the cause of issues like this. I am closing this issue if you can bring any more details or have any ideas what is causing it I am happy to reopen the issue and continue to do my best to help. Sorry for not being able to help.
