### ISSUE TITLE
Suggestion: Support for Amazon Prime Video & Prime Music

### ISSUE THREAD

**Issue by its-thomas** [oscartbeaumont/ElectronPlayer#39]
Hi there!

As a passionate Lubuntu user, I just stumbled upon ElectronPlayer and so far, I am happy: It's definitely lighter (RAM-wise) than my Google-Chrome-for-Netflix solution as far as I can tell. Thanks for putting in the work!

Now, I also am subscribed to Amazon Prime Video & Prime Music and was wondering if you could add support for these also! If you could, then I would have no reason to have Google Chrome installed on my system :-)

Cheers
Thomas

**Comment by its-thomas** [comment]
Errmm...kind of embarrassing: I've just tested Amazon Prime Video & Prime Music with my Firefox 68.0.2 (64-Bit) and after installing some added licences / codecs (which Firefox did automatically after I gave the OK), they both work fine. And out of curiosity, right afterwards I tested Netflix and...well...it also works just fine on my Firefox 68.0.2 (64-Bit)!!!

WOW ...

**Comment by oscartbeaumont** [comment]
Do you still want this integrated?

**Comment by its-thomas** [comment]
Nope, that's not necessary. Thanks for getting back so quickly though :-)

**Comment by Kelvino9** [comment]
> Do you still want this integrated?

Sure @oscartbeaumont , it would be nice if you could add support for Amazon Prime Video

**Comment by oscartbeaumont** [comment]
I am currently very busy but I will add it in a few weeks. If you are interested in adding it earlier you could create a PR. All you have to do is include a logo file preferably an SVG and if possible use the one from the brand assets pages which I assume Amazon would have like Netflix, Hulu and etc have. Then just add it to `src/default-services.js` and test.

**Comment by oscartbeaumont** [comment]
Can someone please test and confirm with me that it works. I personally do not have an account and so don't know if it works. I will release a new version of the app in the near future and hopefully, before that, someone can confirm it works.

**Comment by Kelvino9** [comment]
It works fine. Login didn't work immediately, but I was sent to the Amazon landing page and could login to my account. Had a similar experience with MiniVODViewer when I was still using Windows back then.

Thank you for your efforts!

**Comment by oscartbeaumont** [comment]
When you log in what page are you brought to? I can update it so that it is a better user experience.

**Comment by stefanogreg** [comment]
It seems it is not possible to switch between different Profiles
That would be awesome to have
