### ISSUE TITLE
Adding new services without recompiling

### ISSUE THREAD

**Issue by hariseldon99** [oscartbeaumont/ElectronPlayer#41]
Is it possible to add services without recompiling from source?

**Comment by oscartbeaumont** [comment]
Yes, but I should note the way it is handled has been updated many times notably the current master branch handles it differently than the current public releases.
In the menu go `Settings` > `Edit Config`. It will open the `config.json` file which you can modify. In the current public release (snap or Github Release) it is as easy as copying an existing service and editing it (and you will have to use a `file://` url for the logo).
The current master is still undergoing a few changes including hopefully a GUI option to control the services so I am not going to document its slightly different syntax but that can be found by looking at the commit history and the code. If you can't work it out just email me.

**Comment by gotmax23** [comment]
Hi,

I am running the 2.0.8 appimage. I was wondering how to add a custom service. What do I need to add to my config.json file?

It currently looks like this:
```json
{
	"version": "2.0.8",
	"services": [
		{
			"name": "Amazon Prime Video",
			"hidden": false
		},
		{
			"name": "Twitch",
			"hidden": true
		},
		{
			"name": "Disney+",
			"hidden": false
		}
	],
	"_do_not_edit___date_": 1586273178824,
	"options": {
		"adblock": true
	},
	"relaunch": {}
}
```

Thanks for your help. This is a great project, by the way!

**Comment by oscartbeaumont** [comment]
Go to the default services in the app [here](https://github.com/oscartbeaumont/ElectronPlayer/blob/master/src/default-services.js) to get an idea of the json schema. Hopefully the next update will move to a user interface for managing services to fix issues like this.
