### ISSUE TITLE
Snap version doesn't work on Fedora 31

### ISSUE THREAD

**Issue by roypen** [oscartbeaumont/ElectronPlayer#46]
AppImage works great but Snap version on Fedora 31 returns: "WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement \n 
(electronplayer:7762): Gtk-WARNING **: 22:36:08.690: cannot open display: :0"

**Comment by oscartbeaumont** [comment]
Are you able to run any other snap packages? This seems like an issue with snapcraft. It looks like the process confident used by snaps doesn't fully support cgroup v2. Your version of Fedora has made the move to cgroup v2 as talked about [here](https://www.redhat.com/sysadmin/fedora-31-control-group-v2).
You could fix this by adding the kernel command-line arguments `systemd.unified_cgroup_hierarchy=0` to revert to cgroup v1.

**Comment by roypen** [comment]
Thanks, you are right. There is a problem with all Snap packages.
