### ISSUE TITLE
Added Disney+, mouse pointer and video control issues

### ISSUE THREAD

**Issue by navyguns** [oscartbeaumont/ElectronPlayer#48]
I added Disney+ on the snap on Linux Mint and the Appimage on OpenSuse Tumbleweed. On both systems, I can log in and play videos. However, the mouse pointer disappears when over the electron player window and the video playing cannot be controlled; i.e. paused, stopped, fastforward or reverse. The mouse pointer reappears when moved out of the electronplayer window. Menu items are accessible and work fine.

**Comment by oscartbeaumont** [comment]
I don't have Disney + and have no clue what is causing the issue so I don't know how to proceed on fixing this issue.

**Comment by navyguns** [comment]
Just tried it again. The issue seems to be resolved and all on screen controls are working properly. It was probably an issue in their end. Now if I can get Electronpmayer working on OSMC in my Raspberry Pie. Thank you for your work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
