### ISSUE TITLE
Electron Ad-Blocker

### ISSUE THREAD

**Issue by datumbox** [oscartbeaumont/ElectronPlayer#52]
Thanks for this great snap. I wonder if you have any plans on the future to add an ad-blocker feature on the player. Perhaps use something like [this](https://www.npmjs.com/package/electron-ad-blocker)?

**Comment by oscartbeaumont** [comment]
One has already been added (in issue #14) but has not been released to the snap because I have been super busy. Hopefully, over the next few weeks, it will be released.

**Comment by datumbox** [comment]
Fantastic! The snap version is super convinient. Hope you will get the chance to release a new version soon; there are lots of nice features missing. :)

**Comment by datumbox** [comment]
@oscartbeaumont any news from the snap? :)
