### ISSUE TITLE
Can you add a ad blocker for youtube?

### ISSUE THREAD

**Issue by neogeo71** [oscartbeaumont/ElectronPlayer#54]
ad blocker for youtube?

also just a comment that it sucks to be at the mercy of the streaming companies, Netflix locked ot 720p, amazon 540p, dc universe no issues with 1080p. ridiculous that paying customers get treated this way and you have to pirate on Linux to get higher quality video you are paying for.

Kodi has widevine now for Netflix but the software rendering at 1080p stutters on my lower end laptop. Any idea if you could get the same widevine api or license etc?

Rant over, thanks for this app, it is nice to set up all my streaming services under one app. I know at heart it is just a browser but I dig it just the same.

**Comment by oscartbeaumont** [comment]
Released in v2.0.8
