### ISSUE TITLE
Please can we have an option to turn ad blocking on or off?

### ISSUE THREAD

**Issue by ubuntujaggers** [oscartbeaumont/ElectronPlayer#62]
I'm using the snap available through the Ubuntu store - raising an issue here in case it's common to versions.

One of my streaming services won't let me watch a video because ad blocking is detected (this seems reasonable policy for them to enforce because it's a free streaming service whose revenue comes entirely from ads - if we all had ad blocking on, they'd go out of business).

Could we please have an option, under settings, to turn the global ad blocking on and off?

**Comment by oscartbeaumont** [comment]
The ad blocker was opt in and should by default be enabled and less you enable it from the settings menu.

**Comment by ubuntujaggers** [comment]
Thanks for speedy responses - I don't have that setting in the snap:

![image](https://user-images.githubusercontent.com/38893390/76708619-28263c00-66f0-11ea-9db9-639267c4d6b0.png)

So maybe it's something that affects the snap only, or maybe there's some quirk with the particular streaming service.  Keep up the good work :+1:

**Comment by GordonFreemem** [comment]
@ubuntujaggers Which version are you using? As far as I know adblock is available in v2.0.8. Ubuntu store installs v2.0.7.
If you want to install 2.0.8 you have to change to the beta-channel
`snap refresh electronplayer --channel=latest/beta`

**Comment by oscartbeaumont** [comment]
When I released the Ad Blocker it came disabled by default (very intentionally) and always has. It must be enabled in the "Options" dropdown menu in the app's toolbar. If you have enabled it then disabled it and it hasn't disabled maybe their could be a bug and if so try reinstalling the app.

**Comment by oscartbeaumont** [comment]
> Thanks for speedy responses - I don't have that setting in the snap:
> 
> ![image](https://user-images.githubusercontent.com/38893390/76708619-28263c00-66f0-11ea-9db9-639267c4d6b0.png)
> 
> So maybe it's something that affects the snap only, or maybe there's some quirk with the particular streaming service. Keep up the good work 👍

If you don't have the option in the menu, you don't have a version of the app with support for adblocking.
