### ISSUE TITLE
Will not work on ubuntu with express-vpn

### ISSUE THREAD

**Issue by Lts-Chimera** [oscartbeaumont/ElectronPlayer#74]
i use Ubuntu with express-vpn idk if it's with all vpn's but for some reason with express-vpn i get a see-through screen when connected to the vpn.

![Screenshot from 2020-07-29 00-44-49](https://user-images.githubusercontent.com/68260238/88767285-aaab1780-d136-11ea-815f-1c84f0013350.png)
![Screenshot from 2020-07-29 00-46-18](https://user-images.githubusercontent.com/68260238/88767289-ad0d7180-d136-11ea-96e4-7f23c8ddfd21.png)

**Comment by oscartbeaumont** [comment]
The invisible window is because it is unable to load the website. You can see more details in the developer tools (in the `Developer` section of the menu). I don't know why it's not working but do other applications work with the VPN enabled? What is being blocked in the developer tools?

**Comment by linuxguy99** [comment]
yes other applications do work. it says the display is blocked.

**Comment by oscartbeaumont** [comment]
By any chance can you send a screenshot of the console, I have no idea why this is happening and seeing that might help. Is the menu able to load or not?

**Comment by linuxguy99** [comment]
the console is empty. but here are the elements i don't know if that's what you meant. let me know if you need more info or screenshots

![Screenshot from 2020-08-05 20-52-31](https://user-images.githubusercontent.com/68260238/89485382-e3ae4200-d75d-11ea-9a67-379d2b25d143.png)
![Screenshot from 2020-08-05 20-53-04](https://user-images.githubusercontent.com/68260238/89485386-e5780580-d75d-11ea-96cb-98e912bdd593.png)
